# Refer to https://github.com/Snowfork/snowbridge/blob/464700b8e2dc2bc68abf87dff535ce41e48cc8e0/core/packages/test/scripts/start-services.sh

version: "3.9"
services:
  # Sets up the genesis configuration for the go-ethereum client from a JSON file.
  geth-genesis:
    image: "ethereum/client-go:v1.10.26"
    command: --datadir=/execution init /execution/genesis.json
    volumes:
      - ./execution:/execution
      - ./execution/genesis.json:/execution/genesis.json

  geth-account1:
    image: "ethereum/client-go:v1.10.26"
    command: --datadir=/execution account import --password /dev/null /config/dev-key0.prv
    volumes:
      - ./execution:/execution
      - ./config:/config
    depends_on:
      geth-genesis:
        condition: service_completed_successfully

  geth-account2:
    image: "ethereum/client-go:v1.10.26"
    command: --datadir=/execution account import --password /dev/null /config/dev-key1.prv
    volumes:
      - ./execution:/execution
      - ./config:/config
    depends_on:
      geth-account1:
        condition: service_completed_successfully

  # Runs the go-ethereum execution client with the specified, unlocked account and necessary
  # APIs to allow for proof-of-stake consensus via Prysm.
  geth:
    image: "ethereum/client-go:v1.10.26"
    command:
      - --networkid=15
      - --datadir=/execution
      - --http
      - --http.api=debug,personal,eth,net,web3,txpool,engine,miner
      - --http.addr=0.0.0.0
      - --rpc.allow-unprotected-txs
      - --rpc.gascap=100000000
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/secret/jwtsecret
      - --allow-insecure-unlock
      - --unlock=0xBe68fC2d8249eb60bfCf0e71D5A0d2F2e292c4eD,0x89b4AB1eF20763630df9743ACF155865600daFF2
      - --password=/dev/null
      - --gcmode=archive
      - --syncmode=full
      - --nodiscover
      - --mine
      - --miner.threads=1
      - --miner.etherbase=0x0000000000000000000000000000000000000000
      - --miner.gasprice=0
    ports:
      - 8551:8551
      - 8545:8545
    depends_on:
      geth-account2:
        condition: service_completed_successfully
    volumes:
      - ./execution:/execution
      - ./jwtsecret:/secret/jwtsecret
    networks:
      eth-localnet:
        ipv4_address: 172.16.239.11

  lodestar:
    # https://hub.docker.com/r/chainsafe/lodestar
    image: 'chainsafe/lodestar:v1.2.2'
    container_name: lodestar
    volumes:
      - ./consensus/lodestar:/data
      - ./jwtsecret:/secret/jwtsecret
    ports:
      - "9000:9000" # P2P port
      - "9596:9596" # REST API port
    command:
      - dev
      - --dataDir=/data
      - --jwt-secret=/secret/jwtsecret
      - --genesisValidators=8
      - --startValidators=0..7
      - --genesisTime
      - ${timestamp}
      - --genesisEth1Hash
      - ${genesisHash}
      - --enr.ip=127.0.0.1
      - --rest
      - --rest.address=0.0.0.0
      - --rest.namespace="beacon,config,events,node,validator,lightclient"
      - --eth1=true
      - --eth1.providerUrls
      - http://172.16.239.11:8545
      - --execution.urls
      - http://172.16.239.11:8551
      - --terminal-total-difficulty-override=0
      - --params.ALTAIR_FORK_EPOCH=0
      - --params.BELLATRIX_FORK_EPOCH=0
      - --reset
    networks:
      eth-localnet:
        ipv4_address: 172.16.239.12

networks:
  eth-localnet:
    name: eth-localnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
